#59 tweak file close
adsabs/ADSfulltext pull request #60
Opened 2017-12-04 21:41 UTC by spacemansteve

tweaks to two places where a thrown error could have circumvented a file close statement.

2017-12-04 22:16 UTC, romanchyla requested changes

2017-12-04 22:16 UTC, romanchyla commented on adsft/extraction.py
> +            ft_source.close()
the trouble here is that ft_source won't exist; so this will cause another exception

2017-12-05 15:51 UTC, spacemansteve commented
Should I try to run some real data through the GrobidPDFExtractor?

2017-12-05 16:17 UTC, marblestation approved these changes
It looks good to me! 👍

2017-12-05 16:21 UTC, merged